### ISSUE TITLE
Filter is not working

### ISSUE THREAD

**Issue by AmitAKB** [michaelbromley/ngx-pagination#185]
Filter is not working when we are using below code. It is showing same error on console.
*ngFor="let rec of record.data.teachers | paginate: config | stringFilter: queryString "

**Comment by michaelbromley** [comment]
I got this issue a few times, so I just added an FAQ section to the docs which answers this: https://github.com/michaelbromley/ngx-pagination#why-does-my-filter-not-work-with-pagination

**Comment by AmitAKB** [comment]
It is showing same error.
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Template parse errors:
The pipe 'filter' could not be found ("
                    </thead>
                    <tbody>
                    <tr *ngFor="let[ERROR ->] rec of record1 | filter: queryString | paginate: config ">
                        <td><input type=""): ng:///DashboardModule/DashboardComponent.html@61:35
Error: Template parse errors:
The pipe 'filter' could not be found ("
                    </thead>
                    <tbody>
                    <tr *ngFor="let[ERROR ->] rec of record1 | filter: queryString | paginate: config ">
                        <td><input type=""): ng:///DashboardModule/DashboardComponent.html@61:35
    at syntaxError (http://localhost:4201/vendor.bundle.js:27996:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:4201/vendor.bundle.js:39108:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:4201/vendor.bundle.js:53153:39)
    at http://localhost:4201/vendor.bundle.js:53073:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:4201/vendor.bundle.js:53073:19)
    at http://localhost:4201/vendor.bundle.js:52960:19
    at Object.then (http://localhost:4201/vendor.bundle.js:27986:156)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4201/vendor.bundle.js:52959:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:4201/vendor.bundle.js:52888:37)
    at syntaxError (http://localhost:4201/vendor.bundle.js:27996:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:4201/vendor.bundle.js:39108:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:4201/vendor.bundle.js:53153:39)
    at http://localhost:4201/vendor.bundle.js:53073:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:4201/vendor.bundle.js:53073:19)
    at http://localhost:4201/vendor.bundle.js:52960:19
    at Object.then (http://localhost:4201/vendor.bundle.js:27986:156)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4201/vendor.bundle.js:52959:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:4201/vendor.bundle.js:52888:37)
    at resolvePromise (http://localhost:4201/polyfills.bundle.js:6315:31)
    at resolvePromise (http://localhost:4201/polyfills.bundle.js:6286:17)
    at http://localhost:4201/polyfills.bundle.js:6363:17
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4201/polyfills.bundle.js:5969:31)
    at Object.onInvokeTask (http://localhost:4201/vendor.bundle.js:57958:37)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:4201/polyfills.bundle.js:5968:36)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (http://localhost:4201/polyfills.bundle.js:5736:47)
    at drainMicroTaskQueue (http://localhost:4201/polyfills.bundle.js:6129:35)
    at <anonymous>
defaultErrorLogger @ core.es5.js:1020
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4562
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.triggerError @ core.es5.js:3993
onHandleError @ core.es5.js:3954
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runGuarded @ zone.js:157
_loop_1 @ zone.js:653
api.microtaskDrainDone @ zone.js:662
drainMicroTaskQueue @ zone.js:592
Promise resolved (async)
scheduleMicroTask @ zone.js:567
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
onScheduleTask @ zone.js:300
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:235
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:255
scheduleResolveOrReject @ zone.js:816
resolvePromise @ zone.js:765
(anonymous) @ zone.js:696
webpackJsonpCallback @ bootstrap ba84f00d8012b4473312:21
(anonymous) @ 0.chunk.js:1

**Comment by michaelbromley** [comment]
> The pipe 'filter' could not be found

This means there is no pipe named 'filter' registered in any NgModule available to this component. Make sure you have defined the filter and declared it in your module.
