### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module 

### ISSUE THREAD

**Issue by Fabiyo-90** [michaelbromley/ngx-pagination#211]
this is the result of ng serve --port 85 or ng build --prod

ERROR in Error: Metadata version mismatch for module E:/PRIVATE_PROJECT/Angular/meetmyshop/node_modules/ngx-pagination/dist/ngx-pagination.d.ts, found version 4, expected 3, resolving symbol AppModule in E:/PRIVATE_PROJECT/Angular/meetmyshop/src/app/app.module.ts, resolving symbol AppModule in E:/PRIVATE_PROJECT/Angular/meetmyshop/src/app/app.module.ts
    at syntaxError (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@ngtools\webpack\src\plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (E:\PRIVATE_PROJECT\Angular\meetmyshop\node_modules\@ngtools\webpack\src\plugin.js:448:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Fabiyo-90** [comment]
I use 

@angular/cli: 1.4.7
node: 8.7.0
os: win32 x64
@angular/animations: 4.4.5
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.7
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
typescript: 2.3.4

**Comment by Fabiyo-90** [comment]
I use 👍 
angular/cli: 1.4.7
node: 8.7.0
os: win32 x64
angular/animations: 4.4.5
angular/common: 4.4.5
angular/compiler: 4.4.5
angular/core: 4.4.5
angular/forms: 4.4.5
angular/http: 4.4.5
angular/platform-browser: 4.4.5
angular/platform-browser-dynamic: 4.4.5
angular/router: 4.4.5
angular/cli: 1.4.7
angular/compiler-cli: 4.4.5
angular/language-service: 4.4.5
typescript: 2.3.4

**Comment by michaelbromley** [comment]
What version of ngx-pagination are you using? This sounds like an issue with 3.0.2. If so, try upgrading to 3.0.3.

**Comment by Fabiyo-90** [comment]
Ok thanks ! 
Now it is working
