### ISSUE TITLE
Missing pipe: paginate

### ISSUE THREAD

**Issue by SafarAli-SS** [michaelbromley/ngx-pagination#311]
**Angular version**:~8.1.0

**ngx-pagination version**:^4.0.0

**Description of issue**:
Hi, ngx-pagination works well in development, it compiles successfully. But when I want to compile it for production with ng build --prod command it fails showing that pipe paginate is missing.

**Steps to reproduce**:

**Expected result**:

**Actual result**:
ERROR in : Error: Missing pipe: paginate
    at Context.getPipeByName (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:425:23)
    at tcbResolve (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:900:28)
    at AstTranslator.maybeResolve (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:774:74)
    at AstTranslator.translate (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:63:33)
    at Object.astToTypescript (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:48:27)
    at tcbExpression (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:774:29)
    at processAttribute (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:821:28)
    at Array.forEach (<anonymous>)
    at tcbGetInputBindingExpressions (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:811:30)
    at TcbDirectiveOp.execute (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:306:28)
    at Scope.executeOp (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:641:26)
    at Scope.render (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:580:22)
    at Object.generateTypeCheckBlock (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:43:37)
    at TypeCheckFile.addTypeCheckBlock (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_file.js:45:41)
    at TypeCheckContext.addTemplate (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/context.js:98:36)
    at ComponentDecoratorHandler.typeCheck (/media/safarali/2C10689810686B32/Documents/Angular/digitalbum/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:365:21)

Any relevant code:
```my app.component.html file
`<div class="searchbox" id="top">
    <h1>DigitAlbum</h1>
    <div class="search">
      <input
        type="text"
        #input
        [(ngModel)]="query"
        placeholder="search photos"
        required
      />
      <button
        type="submit"
        (click)="onSearch(query); query = ''"
        [disabled]="!query"
      >
        <i class="material-icons">
          image_search
        </i>
      </button>
    </div>
    <!-- <p *ngIf="isLoading">Loading images, please wait a bit...</p> -->
    <div *ngIf="isLoading" class="loading"></div>
  </div>

<div class="img-box">
  <figure
    *ngFor="
      let image of images
        | async
        | paginate: { itemsPerPage: 10, currentPage: p }
    "
  >
    <a href="{{ image.pageURL }}" target="_blank">
      <img src="{{ image.webformatURL }}" />
    </a>
  </figure>
</div>
<p
  *ngIf="noResults"
  style="text-align: center; color: rgb(185, 40, 40);"
  [hidden]="isLoading"
>
  Sorry, there are no images with that title.
</p>
<pagination-controls
  [hidden]="noResults"
  *ngIf="images"
  (pageChange)="p = $event"
  class="pagination"
></pagination-controls>


import { Component, OnInit } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { map } from "rxjs/operators";
import { environment } from "../environments/environment";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent implements OnInit {
  isLoading: boolean;
  p = 1;
  query;
  noResults: boolean;
  images;

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.onSearch("photos");
  }

  onSearch(query) {
    this.isLoading = true;
    let URL = `https://pixabay.com/api/?key=${
      environment.PIXABAY_API_KEY
    }&q=${query}&per_page=200&page=1&safesearch=true`;
    console.log(query);
    this.images = this.http.get(URL).pipe(
      map((data: any) => {
        if (data.total === 0) {
          this.noResults = true;
        } else {
          this.noResults = false;
        }
        console.log(data);
        this.isLoading = false;
        return data.hits;
      })
    );
    this.p = 1;
    return this.images;
  }
}`
```
``

**Comment by cloudhuang** [comment]
Get the same issue in development env. following is the env info:
```
Angular CLI: 8.3.24
Node: 13.6.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.24
@angular-devkit/build-angular     0.803.24
@angular-devkit/build-optimizer   0.803.24
@angular-devkit/build-webpack     0.803.24
@angular-devkit/core              8.3.24
@angular-devkit/schematics        8.3.24
@angular/cli                      8.3.24
@ngtools/webpack                  8.3.24
@schematics/angular               8.3.24
@schematics/update                0.803.24
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```
ngx-pagination version: ` "ngx-pagination": "^5.0.0",`
